### ISSUE TITLE
Html and PHP files are corrupted

### ISSUE THREAD

**Issue by gremlin97** [Gokulvasudev/Mini-Project#1]
After downloading the project I have found out that many of the html and php files  are corrupted.Please can u upload or resend the correct files.

Regards,
gremlin97

**Comment by Gokulvasudev** [comment]
Sure.Thank you for the mail.

**Comment by gremlin97** [comment]
Sir please can u send me the correct files.I had some urgent work regarding
them.

**Comment by Gokulvasudev** [comment]
All files are updated.Please take a look.The files are also in the zip file.Please create a database according to the code and corresponding tables which i didn't uploaded here.
